///This file is automatically generated. DO NOT EDIT, all your changes would be lost.
class Memojis {
  Memojis._();

  static const String memoji1 = 'assets/images/memoji/1.png';
  static const String memoji2 = 'assets/images/memoji/2.png';
  static const String memoji3 = 'assets/images/memoji/3.png';
  static const String memoji4 = 'assets/images/memoji/4.png';
  static const String memoji5 = 'assets/images/memoji/5.png';
  static const String memoji6 = 'assets/images/memoji/6.png';
  static const String memoji7 = 'assets/images/memoji/7.png';
  static const String memoji8 = 'assets/images/memoji/8.png';
  static const String memoji9 = 'assets/images/memoji/9.png';
}

List memojiPaths = [
  Memojis.memoji1,
  Memojis.memoji2,
  Memojis.memoji3,
  Memojis.memoji4,
  Memojis.memoji5,
  Memojis.memoji6,
  Memojis.memoji7,
  Memojis.memoji8,
  Memojis.memoji9,
];
